version: "3"

services:
  app:
    image: golang:1.8.1
    stdin_open: true
    container_name: vg-1day-2017-go
    volumes:
      - .:/go/src/github.com/VG-Tech-Dojo/vg-1day-2017
    ports:
      - 8088:8080
    working_dir: /go/src/github.com/VG-Tech-Dojo/vg-1day-2017
